receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  aclreceiver: # this line represents the ID of your receiver

processors:
  batch:

exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed
service:
  pipelines:
    metrics:
      receivers: [aclreceiver]
      processors: [batch]
      exporters: [debug]
  telemetry:
    logs:
      level: debug
